export const recentTrips = [
    {
      id: "1",
      from: "Bole",
      to: "Piassa",
      date: "Today",
      time: "08:30 AM",
      status: "Completed",
      price: "35 ETB",
    },
    {
      id: "2",
      from: "Megenagna",
      to: "Mexico Square",
      date: "Yesterday",
      time: "02:15 PM",
      status: "Completed",
      price: "25 ETB",
    },
    {
      id: "3",
      from: "Stadium",
      to: "Bole",
      date: "May 20",
      time: "09:45 AM",
      status: "Cancelled",
      price: "40 ETB",
    },
    {
      id: "4",
      from: "Stadium",
      to: "Bole",
      date: "May 20",
      time: "09:45 AM",
      status: "Cancelled",
      price: "40 ETB",
    },
    {
      id: "5",
      from: "Stadium",
      to: "Bole",
      date: "May 20",
      time: "09:45 AM",
      status: "Cancelled",
      price: "40 ETB",
    },
    {
      id: "6",
      from: "Stadium",
      to: "Bole",
      date: "May 20",
      time: "09:45 AM",
      status: "Cancelled",
      price: "40 ETB",
    },
    {
      id: "7",
      from: "Stadium",
      to: "Bole",
      date: "May 20",
      time: "09:45 AM",
      status: "Cancelled",
      price: "40 ETB",
    },
    {
      id: "8",
      from: "Stadium",
      to: "Bole",
      date: "May 20",
      time: "09:45 AM",
      status: "Cancelled",
      price: "40 ETB",
    },
  ];
  
  export const popularDestinations = [
    {
      id: "1",
      name: "Bole International Airport",
      icon: "plane",
    },
    {
      id: "2",
      name: "Meskel Square",
      icon: "map-pin",
    },
    {
      id: "3",
      name: "Unity Park",
      icon: "tree",
    },
    {
      id: "4",
      name: "Merkato",
      icon: "shopping-bag",
    },
    {
      id: "5",
      name: "Unity Park",
      icon: "tree",
    },
    {
      id: "6",
      name: "Unity Park",
      icon: "tree",
    },
    {
      id: "7",
      name: "Unity Park",
      icon: "tree",
    },
    {
      id: "8",
      name: "Unity Park",
      icon: "tree",
    },
  ];
  
  export const nearbyVehicles = [
    {
      id: "1",
      type: "Bus",
      number: "105",
      route: "Bole to Piassa",
      eta: "3 min",
      crowdLevel: "Low",
      distance: "0.5 km",
    },
    {
      id: "2",
      type: "Taxi",
      number: "AET-1234",
      driver: "Alemu T.",
      rating: 4.8,
      eta: "5 min",
      distance: "0.8 km",
    },
    {
      id: "3",
      type: "Train",
      line: "Green Line",
      route: "East-West",
      eta: "7 min",
      crowdLevel: "Medium",
      distance: "1.2 km",
    },
    {
      id: "4",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      eta: "7 min",
      crowdLevel: "Medium",
      distance: "1.2 km",
    },
    {
      id: "5",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      eta: "7 min",
      crowdLevel: "Medium",
      distance: "1.2 km",
    },
    {
      id: "6",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      eta: "7 min",
      crowdLevel: "Medium",
      distance: "1.2 km",
    },
    {
      id: "7",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      eta: "7 min",
      crowdLevel: "Medium",
      distance: "1.2 km",
    },
    {
      id: "8",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      eta: "7 min",
      crowdLevel: "Medium",
      distance: "1.2 km",
    },
  ];
  
  export const schedules = [
    {
      id: "1",
      type: "Bus",
      number: "105",
      route: "Bole to Piassa",
      departures: ["06:00", "06:30", "07:00", "07:30", "08:00", "08:30"],
      price: "15 ETB",
    },
    {
      id: "2",
      type: "Bus",
      number: "72",
      route: "Megenagna to Mexico",
      departures: ["06:15", "06:45", "07:15", "07:45", "08:15", "08:45"],
      price: "12 ETB",
    },
    {
      id: "3",
      type: "Train",
      line: "Green Line",
      route: "East-West",
      departures: ["06:00", "06:20", "06:40", "07:00", "07:20", "07:40"],
      price: "10 ETB",
    },
    {
      id: "4",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      departures: ["06:00", "06:20", "06:40", "07:00", "07:20", "07:40"],
      price: "10 ETB",
    },
    {
      id: "5",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      departures: ["06:00", "06:20", "06:40", "07:00", "07:20", "07:40"],
      price: "10 ETB",
    },
    {
      id: "6",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      departures: ["06:00", "06:20", "06:40", "07:00", "07:20", "07:40"],
      price: "10 ETB",
    },
    {
      id: "7",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      departures: ["06:00", "06:20", "06:40", "07:00", "07:20", "07:40"],
      price: "10 ETB",
    },
    {
      id: "8",
      type: "Train",
      line: "Blue Line",
      route: "North-South",
      departures: ["06:00", "06:20", "06:40", "07:00", "07:20", "07:40"],
      price: "10 ETB",
    },
  ];
  
  export const userProfile = {
    name: "Abebe Kebede",
    phone: "+251 91 234 5678",
    email: "abebe@example.com",
    points: 350,
    level: "Silver",
    savedLocations: [
      { id: "1", name: "Home", address: "Bole, Addis Ababa" },
      { id: "2", name: "Work", address: "Kazanchis, Addis Ababa" },
      { id: "3", name: "Gym", address: "Meskel Square, Addis Ababa" },
    ],
  };